### ISSUE TITLE
cdk-dynamo-table-viewer incompatible with CDK 1.106.0

### ISSUE THREAD

**Issue by gliptak** [cdklabs/cdk-dynamo-table-viewer#41]
```
    aws-cdk-aws-sns 1.106.0 depends on jsii<2.0.0 and >=1.29.0
    aws-cdk-cx-api 1.106.0 depends on jsii<2.0.0 and >=1.29.0
    aws-cdk-region-info 1.106.0 depends on jsii<2.0.0 and >=1.29.0
    cdk-dynamo-table-viewer 3.1.2 depends on jsii~=0.21.1
```

Current master seem to have been updated https://github.com/cdklabs/cdk-dynamo-table-viewer/blob/master/package.json#L45

https://github.com/cdklabs/cdk-dynamo-table-viewer/issues/13

**Comment by gliptak** [comment]
There are two packages on PyPi

https://pypi.org/project/cdk-dynamo-table-viewer/
https://pypi.org/project/cdk-dynamo-table-view/

**Comment by gliptak** [comment]
Corrected this requiring `"cdk-dynamo-table-view==0.1.19",`

**Comment by GrahamLea** [comment]
@gliptak Did the above mean #13 is fixed?

**Comment by gliptak** [comment]
@GrahamLea yes HEAD / right PyPI package works with latest CDK 1.x

The documentation might want to capture the right PyPi package name
