### ISSUE TITLE
[Q] How it works in real-time?

### ISSUE THREAD

**Issue by Tolluset** [cdklabs/cdk-dynamo-table-viewer#54]
I didn't see any polling code, or using socket by API GW.

So, how can this library render real-time at requests?

>

**Comment by Tolluset** [comment]
So, it just using promise to make pending status?

And now it's in pending status, then the scan dynamodb continuously? WOW

**Comment by philals** [comment]
Also uses this tag in the HTML https://www.w3schools.com/tags/att_meta_http_equiv.asp
